---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: dev
spec:
  selector:
    app: mysqldb
    type: back-end
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP  # default, can be omitted
